name: MNA and IPO Watcher

on:
  schedule:
    - cron: '*/15 * * * *'  # Každých 15 minút
  workflow_dispatch:

jobs:
  run-watcher:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Timeout po 10 minútach
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Initialize database
      run: python init_db.py

    - name: Run MNA and IPO Watcher
      env:
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: python main.py
